import rawImported from '../data/imported.json';
import rawAdditives from '../data/additives.json';
import rawCategories from '../data/categories.json';
import { Additive, Category, Food, SafetyResult } from '../types';
import { scoreFood } from './scoring';

/**
 * The single place the app talks to the dataset.
 *
 * Swapping in a new dataset means replacing the three JSON files and nothing
 * else. `normalise` absorbs the small differences a hand-authored file tends
 * to have (nulls instead of missing keys, absent optional arrays) so the rest
 * of the app can rely on the shapes in types.ts.
 */

function normaliseFood(f: any): Food {
  return {
    id: String(f.id),
    name: String(f.name),
    brand: f.brand ?? '',
    categoryId: f.categoryId,
    emoji: f.emoji ?? '🍽️',
    processing: f.processing ?? 'processed',
    keywords: f.keywords ?? [],
    serving: f.serving ?? { amount: 100, unit: 'g', label: '100 g' },
    // JSON has no `undefined`, so a food with no countable unit arrives as null.
    piece: f.piece ?? undefined,
    nutrition: {
      energyKcal: num(f.nutrition?.energyKcal),
      fatG: num(f.nutrition?.fatG),
      satFatG: num(f.nutrition?.satFatG),
      transFatG: num(f.nutrition?.transFatG),
      carbsG: num(f.nutrition?.carbsG),
      sugarG: num(f.nutrition?.sugarG),
      fibreG: num(f.nutrition?.fibreG),
      proteinG: num(f.nutrition?.proteinG),
      sodiumMg: num(f.nutrition?.sodiumMg),
    },
    additives: f.additives ?? [],
    allergens: f.allergens ?? [],
    benefits: f.benefits ?? [],
    warnings: f.warnings ?? [],
    // JSON has no `undefined`, so an unset limit arrives as null.
    safeLimit: f.safeLimit ?? undefined,
    note: f.note ?? '',
  };
}

const num = (v: unknown) => (typeof v === 'number' && isFinite(v) ? v : 0);

/**
 * Every product the scanner can find, generated by `npm run import` from the
 * barcode dumps in `data/`.
 *
 * The old hand-written starter set (apple, dal, roti) is deliberately not
 * loaded any more: those foods have no barcode, so in a scan-only app there is
 * no way to reach them. `src/data/foods.json` is still in the repo if browsing
 * ever comes back.
 */
export const foods: Food[] = (rawImported as any[]).map(normaliseFood);
export const additives: Additive[] = rawAdditives as Additive[];
export const categories: Category[] = rawCategories as Category[];

export const additiveMap: Record<string, Additive> = Object.fromEntries(
  additives.map((a) => [a.id, a])
);

const categoryMap: Record<string, Category> = Object.fromEntries(
  categories.map((c) => [c.id, c])
);

/** Scores are computed once at startup — the dataset does not change at runtime. */
const scoreCache: Record<string, SafetyResult> = Object.fromEntries(
  foods.map((f) => [f.id, scoreFood(f, additiveMap)])
);

export const safetyOf = (food: Food): SafetyResult => scoreCache[food.id];

export const categoryById = (id: string): Category | undefined => categoryMap[id];

const foodIdIndex: Record<string, Food> = Object.fromEntries(foods.map((f) => [f.id, f]));

export const foodById = (id: string): Food | undefined => foodIdIndex[id];

/**
 * Barcode lookup.
 *
 * The same product can be printed as UPC-A (12 digits) and stored as EAN-13
 * (13 digits, padded with a leading zero) — "028400034227" and
 * "0028400034227" are the same tin of soup. Stripping non-digits and leading
 * zeros makes both sides comparable, so a scan matches whichever form the
 * dataset happens to hold.
 */
const normaliseBarcode = (raw: string): string =>
  raw.replace(/\D/g, '').replace(/^0+/, '') || '0';

const barcodeIndex: Record<string, Food> = {};
for (const f of foods) {
  // Only imported products are keyed by barcode; curated ones use slugs.
  if (/^\d{6,}$/.test(f.id)) barcodeIndex[normaliseBarcode(f.id)] = f;
}

export const foodByBarcode = (raw: string): Food | undefined =>
  barcodeIndex[normaliseBarcode(raw)];

/** How many products can actually be found by scanning. Shown on the scanner. */
export const scannableCount = Object.keys(barcodeIndex).length;

export const foodsInCategory = (id: string): Food[] =>
  foods.filter((f) => f.categoryId === id);

/** How many additives of concern a food carries. Used for the list badges. */
export const riskyAdditiveCount = (food: Food): number =>
  food.additives.filter((id) => {
    const a = additiveMap[id];
    return a && a.risk !== 'safe';
  }).length;

export const additivesOf = (food: Food): Additive[] =>
  food.additives
    .map((id) => additiveMap[id])
    .filter(Boolean)
    // Worst first, so the user reads the thing that matters most.
    .sort((a, b) => rank(b.risk) - rank(a.risk));

const rank = (r: string) => ({ safe: 0, low: 1, moderate: 2, high: 3 }[r] ?? 0);
