import rawFoods from '../data/foods.json';
import rawImported from '../data/imported.json';
import rawAdditives from '../data/additives.json';
import rawCategories from '../data/categories.json';
import { Additive, Category, Food, SafetyResult } from '../types';
import { scoreFood } from './scoring';

/**
 * The single place the app talks to the dataset.
 *
 * Swapping in a new dataset means replacing the three JSON files and nothing
 * else. `normalise` absorbs the small differences a hand-authored file tends
 * to have (nulls instead of missing keys, absent optional arrays) so the rest
 * of the app can rely on the shapes in types.ts.
 */

function normaliseFood(f: any): Food {
  return {
    id: String(f.id),
    name: String(f.name),
    brand: f.brand ?? '',
    categoryId: f.categoryId,
    emoji: f.emoji ?? '🍽️',
    processing: f.processing ?? 'processed',
    keywords: f.keywords ?? [],
    serving: f.serving ?? { amount: 100, unit: 'g', label: '100 g' },
    // JSON has no `undefined`, so a food with no countable unit arrives as null.
    piece: f.piece ?? undefined,
    nutrition: {
      energyKcal: num(f.nutrition?.energyKcal),
      fatG: num(f.nutrition?.fatG),
      satFatG: num(f.nutrition?.satFatG),
      transFatG: num(f.nutrition?.transFatG),
      carbsG: num(f.nutrition?.carbsG),
      sugarG: num(f.nutrition?.sugarG),
      fibreG: num(f.nutrition?.fibreG),
      proteinG: num(f.nutrition?.proteinG),
      sodiumMg: num(f.nutrition?.sodiumMg),
    },
    additives: f.additives ?? [],
    allergens: f.allergens ?? [],
    benefits: f.benefits ?? [],
    warnings: f.warnings ?? [],
    // JSON has no `undefined`, so an unset limit arrives as null.
    safeLimit: f.safeLimit ?? undefined,
    note: f.note ?? '',
  };
}

const num = (v: unknown) => (typeof v === 'number' && isFinite(v) ? v : 0);

/**
 * Two sources, one list:
 *  - foods.json    the curated starter set, written by hand
 *  - imported.json real products generated by `npm run import` from data/
 *
 * A barcode in imported.json wins over a curated entry with the same id, so
 * real label data always beats the hand-written stand-in.
 */
const merged = new Map<string, Food>();
for (const f of rawFoods as any[]) merged.set(String(f.id), normaliseFood(f));
for (const f of rawImported as any[]) merged.set(String(f.id), normaliseFood(f));

export const foods: Food[] = [...merged.values()];
export const additives: Additive[] = rawAdditives as Additive[];
export const categories: Category[] = rawCategories as Category[];

export const additiveMap: Record<string, Additive> = Object.fromEntries(
  additives.map((a) => [a.id, a])
);

const categoryMap: Record<string, Category> = Object.fromEntries(
  categories.map((c) => [c.id, c])
);

/** Scores are computed once at startup — the dataset does not change at runtime. */
const scoreCache: Record<string, SafetyResult> = Object.fromEntries(
  foods.map((f) => [f.id, scoreFood(f, additiveMap)])
);

export const safetyOf = (food: Food): SafetyResult => scoreCache[food.id];

export const categoryById = (id: string): Category | undefined => categoryMap[id];

export const foodById = (id: string): Food | undefined =>
  foods.find((f) => f.id === id);

export const foodsInCategory = (id: string): Food[] =>
  foods.filter((f) => f.categoryId === id);

/** How many additives of concern a food carries. Used for the list badges. */
export const riskyAdditiveCount = (food: Food): number =>
  food.additives.filter((id) => {
    const a = additiveMap[id];
    return a && a.risk !== 'safe';
  }).length;

export const additivesOf = (food: Food): Additive[] =>
  food.additives
    .map((id) => additiveMap[id])
    .filter(Boolean)
    // Worst first, so the user reads the thing that matters most.
    .sort((a, b) => rank(b.risk) - rank(a.risk));

const rank = (r: string) => ({ safe: 0, low: 1, moderate: 2, high: 3 }[r] ?? 0);

export interface SearchHit {
  food: Food;
  /** Higher is a better match. */
  score: number;
}

/** Lower-cased name, code and aliases of everything a food contains. Cached. */
const additiveTextCache: Record<string, string> = {};
function additiveTextFor(food: Food): string {
  if (additiveTextCache[food.id] === undefined) {
    additiveTextCache[food.id] = food.additives
      .map((id) => additiveMap[id])
      .filter(Boolean)
      .flatMap((a) => [a.name, a.code, ...a.aliases])
      .join(' ')
      .toLowerCase();
  }
  return additiveTextCache[food.id];
}

/**
 * Ranked substring search over name, brand, category and keywords.
 * Deliberately forgiving — people type "chips", "maggi" or "cold drink".
 */
export function searchFoods(query: string): Food[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const terms = q.split(/\s+/);
  const hits: SearchHit[] = [];

  for (const food of foods) {
    const name = food.name.toLowerCase();
    const haystack = [
      name,
      food.brand.toLowerCase(),
      categoryMap[food.categoryId]?.name.toLowerCase() ?? '',
      ...food.keywords.map((k) => k.toLowerCase()),
    ];
    // Searching "msg", "E621" or "palm oil" should find the foods containing it.
    const additiveText = additiveTextFor(food);

    let score = 0;
    for (const term of terms) {
      let termScore = 0;
      if (name === term) termScore = 100;
      else if (name.startsWith(term)) termScore = 60;
      else if (name.includes(term)) termScore = 40;
      else if (food.keywords.some((k) => k.toLowerCase() === term)) termScore = 50;
      else if (haystack.some((h) => h.includes(term))) termScore = 20;
      else if (additiveText.includes(term)) termScore = 15;
      // Every term has to land somewhere, otherwise it is not a match.
      if (termScore === 0) {
        score = 0;
        break;
      }
      score += termScore;
    }

    if (score > 0) hits.push({ food, score });
  }

  return hits
    .sort((a, b) => b.score - a.score || a.food.name.localeCompare(b.food.name))
    .map((h) => h.food);
}

/** Search the additive database directly, so "E621" or "msg" finds the entry. */
export function searchAdditives(query: string): Additive[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return additives.filter(
    (a) =>
      a.name.toLowerCase().includes(q) ||
      a.code.toLowerCase().includes(q) ||
      a.class.toLowerCase().includes(q) ||
      a.aliases.some((alias) => alias.includes(q))
  );
}
